default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: test-api_development

production:
  <<: *default
  database: test-api_production
  username:
  password:
